version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.env
  database-gui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.env
